version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: genosentinel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genosentinel
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - genosentinel-network

  auth-service:
    build: ./auth-service
    container_name: genosentinel-auth
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=genosentinel
      - JWT_SECRET=tu_jwt_secret_super_seguro_aqui_cambiar_en_produccion
      - JWT_EXPIRES_IN=24h
      - CLINICAL_SERVICE_URL=http://clinical-service:3011
      - GENOMICS_SERVICE_URL=http://genomics-service:3012
    depends_on:
      - mysql
    networks:
      - genosentinel-network

volumes:
  mysql_data:

networks:
  genosentinel-network:
    driver: bridge