apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: genosentinel
type: Opaque
data:
  # Las contrase√±as deben estar en BASE64
  # "root" en base64 es "cm9vdA=="
  mysql-root-password: cm9vdA==
  mysql-user: cm9vdA==
  mysql-password: cm9vdA==
  
  # JWT secret en base64
  # "genosentinel-jwt-secret-2024" en base64
  jwt-secret: Z2Vub3NlbnRpbmVsLWp3dC1zZWNyZXQtMjAyNA==