apiVersion: v1
kind: ConfigMap
metadata:
  name: genomics-config
  namespace: genosentinel
data:
  # Configuraci贸n del servicio
  SERVICE_PORT: "3002"
  NODE_ENV: "production"
  
  # Configuraci贸n de base de datos
  DB_HOST: "genomics-mysql-service"
  DB_PORT: "3306"
  DB_NAME: "genomica_db"
  
  # Configuraci贸n de la aplicaci贸n
  CORS_ORIGIN: "http://localhost:3000,http://localhost:3010"
  LOG_LEVEL: "info"
  
  # URLs de otros servicios
  CLINICAL_SERVICE_URL: "http://clinical-service:3020"