apiVersion: v1
kind: Service
metadata:
  name: clinical-service
  namespace: genosentinel
  labels:
    app: clinical-service
    component: microservice
spec:
  selector:
    app: clinical-service
  ports:
  - port: 3020
    targetPort: 3020
  type: ClusterIP
  # ClusterIP: solo accesible dentro del cluster
  # El Gateway (auth-service) accede a este servicio internamente