apiVersion: v1
kind: Service
metadata:
  name: genomics-service
  namespace: genosentinel
  labels:
    app: genomics-service
    component: microservice
spec:
  selector:
    app: genomics-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
  # ClusterIP: solo accesible dentro del cluster
  # El Gateway (auth-service) accede a este servicio internamente