apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-service
  namespace: genosentinel
  labels:
    app: mysql-auth
    component: database
spec:
  selector:
    app: mysql-auth
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP