apiVersion: v1
kind: Service
metadata:
  name: genomics-mysql-service
  namespace: genosentinel
  labels:
    app: mysql-genomics
    component: database
spec:
  selector:
    app: mysql-genomics
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP