apiVersion: v1
kind: Service
metadata:
  name: clinical-mysql-service
  namespace: genosentinel
  labels:
    app: mysql-clinical
    component: database
spec:
  selector:
    app: mysql-clinical
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP